name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Voting App to Heroku
      env:
        HEROKU_API_TOKEN: "API_TOKEN"
        HEROKU_APP_NAME: "jm-voting-app"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        echo https://heroku:${HEROKU_API_TOKEN}@git.heroku.com/${HEROKU_APP_NAME}.git
        git subtree push --prefix=Back_End_Development_Certification/Voting_App "https://heroku:${HEROKU_API_TOKEN}@git.heroku.com/${HEROKU_APP_NAME}.git" origin/master:master

