name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Voting App to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        echo "https://heroku:${HEROKU_API_TOKEN}%40git.heroku.com/jm-voting-app.git"
        git subtree push --prefix=Back_End_Development_Certification/Voting_App "https://heroku:${HEROKU_API_TOKEN}$40git.heroku.com/jm-voting-app.git" origin/master:master

